name: app_new
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  animate_do: ^3.1.2
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  just_audio: ^0.9.34
  get: ^4.6.6
  go_router: ^12.0.0
  dio: ^5.3.3
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg/
    - assets/logo/
    - assets/friend_web/
    - assets/other/
    - assets/posts/
    - assets/role/
    - assets/posts/first.md
    - assets/posts/privacy.md
    - assets/posts/taptap_qbj.md
    - assets/posts/taptap.md
